// st-hum.mjs <dist>: the hum's state, level and pitch on the cover, slide 2, the close and the presenter view.
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { chromium } from 'playwright-chromium';
const DIST = process.argv[2];
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.woff2': 'font/woff2', '.svg': 'image/svg+xml', '.png': 'image/png' };
const srv = createServer(async (req, res) => { let p = decodeURIComponent(new URL(req.url, 'http://x').pathname); if (p === '/') p = '/index.html'; try { await stat(join(DIST, p)); } catch { p = '/index.html'; } res.setHeader('Content-Type', MIME[extname(p)] || 'application/octet-stream'); res.end(await readFile(join(DIST, p))); }).listen(8778);
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const logs = [];
page.on('console', (m) => { if ((m.type() === 'error' || m.type() === 'warning') && !/preload/.test(m.text())) logs.push(m.type() + ': ' + m.text().slice(0, 160)); });
page.on('pageerror', (e) => logs.push('pageerror: ' + e.message.slice(0, 160)));
const state = async (label) => console.log(label.padEnd(30), JSON.stringify(await page.evaluate(() => { const el = document.querySelector('.hadron-space'); return { hum: el?.dataset.hum ?? null, at: el?.dataset.spaceAt ?? null, probe: el?.__hum ? el.__hum() : null }; })));
await page.goto('http://localhost:8778/#/1'); await page.waitForTimeout(4000);
await state('cover, no key yet');
await page.keyboard.press('Shift'); await page.waitForTimeout(4000);
await state('cover, 4 s after a key');
await page.evaluate(() => { location.hash = '#/2'; }); await page.waitForTimeout(1000);
await state('slide 2, 1 s');
await page.waitForTimeout(3000);
await state('slide 2, 4 s');
await page.evaluate(() => { location.hash = "#/27"; }); await page.waitForTimeout(16000);
await state('close, 16 s');
await page.goto('http://localhost:8778/#/presenter/1'); await page.waitForTimeout(5000);
await page.keyboard.press('Shift'); await page.waitForTimeout(3000);
await state('presenter cover, after a key');
console.log(JSON.stringify({ logs: logs.slice(0, 8) }));
await browser.close(); srv.close();
